import { Router } from 'express';
import { pool } from '../db.js';
import { getOrCreateUserByTelegramId } from '../services/users.js';
import { holdRewardFromAdEvent, countTodayAdEvents } from '../services/ledger.js';

export const monetagRouter = Router();

/**
 * Monetag S2S postback — corrected against Monetag's OFFICIAL SDK reference
 * (docs.monetag.com/docs/sdk-reference/), fetched and read directly.
 *
 * IMPORTANT CORRECTION from the earlier version of this file: `ymid` is NOT
 * generated by Monetag - it is a value WE set on the client-side call, and
 * Monetag echoes it back in the postback so we can match the two up. Official
 * docs: "ymid (string, optional) - Custom event or user identifier. Used to
 * match the frontend call with backend postbacks."
 *
 * `requestVar` is NOT a place to smuggle the user ID either - official docs:
 * "Custom label for the placement or ad trigger source. Used in analytics...
 * lets you analyze monetization by source." Examples given: 'level_end',
 * 'bonus_button'. We use it for exactly that: which Earn-tab placement
 * triggered this ad ('watch_and_earn', 'spin', 'sponsored_task').
 *
 * Design: on the client, we generate ymid ourselves as
 *   `${telegramId}:${Date.now()}:${randomNonce}`
 * before calling show_<zone>({ type: 'end', ymid, requestVar: 'watch_and_earn' }).
 * That same ymid comes back in this postback, giving us BOTH a real identifier
 * to parse the Telegram user ID out of AND a genuinely unique value per
 * attempt for idempotency - no synthetic/guessed ID needed, unlike AdsGram.
 */
monetagRouter.get('/reward', async (req, res) => {
  const { secret, ymid, zone_id, sub_zone_id, request_var, event_type, reward_event_type, estimated_price } = req.query;

  if (!secret || secret !== process.env.MONETAG_POSTBACK_SECRET) {
    return res.status(401).json({ error: 'invalid_secret' });
  }
  if (!ymid) {
    return res.status(400).json({ error: 'missing_ymid' });
  }

  // ymid shape we control: "<telegramId>:<timestamp>:<nonce>"
  const telegramId = String(ymid).split(':')[0];
  if (!telegramId) {
    return res.status(400).json({ error: 'malformed_ymid' });
  }

  // Only a genuinely "valued" impression counts. A non-valued event is
  // acknowledged (200, so Monetag doesn't retry) but never credited, and
  // does not consume the user's daily view allowance.
  if (reward_event_type !== 'valued') {
    return res.status(200).json({ ok: true, credited: false, reason: 'not_valued' });
  }

  const grossPayout = Number(estimated_price);
  if (!Number.isFinite(grossPayout) || grossPayout <= 0) {
    // Don't guess a fallback the way we had to for AdsGram - if Monetag
    // didn't send a real price, we don't know what to pay, so we refuse
    // rather than invent a number.
    console.error('[monetag webhook] missing/invalid estimated_price for ymid', ymid);
    return res.status(200).json({ ok: true, credited: false, reason: 'no_price_data' });
  }

  try {
    const internalUserId = await getOrCreateUserByTelegramId(telegramId);

    // Real daily cap - was never enforced server-side before (only a 20s-class
    // cooldown existed on the AdsGram side). See ledger.js comment for why this
    // is flat rather than tier-aware for now.
    const todayCount = await countTodayAdEvents(pool, internalUserId);
    const dailyCap = Number(process.env.DAILY_VIEW_CAP ?? 80);
    if (todayCount >= dailyCap) {
      return res.status(200).json({ ok: true, credited: false, reason: 'daily_cap_reached' });
    }

    // Same reward-pool formula as AdsGram (Phase 2 unit-economics framework),
    // fed with Monetag's REAL per-event price instead of a configured estimate.
    const fraudReservePct = Number(process.env.FRAUD_RESERVE_PCT ?? 0.08);
    const payoutCostPct = Number(process.env.PAYOUT_COST_PCT ?? 0.02);
    const infraReservePct = Number(process.env.INFRA_RESERVE_PCT ?? 0.10);
    const rewardPoolPct = Number(process.env.REWARD_POOL_PCT ?? 0.45);
    const eligibleRevenue = grossPayout * (1 - fraudReservePct - payoutCostPct - infraReservePct);
    const userReward = eligibleRevenue * rewardPoolPct;

    const result = await holdRewardFromAdEvent({
      userId: internalUserId,
      networkName: 'monetag',
      externalEventId: String(ymid), // real, self-generated-but-unique per attempt
      grossPayout,
      userRewardAmount: userReward,
      rawPayload: { zoneId: zone_id, subZoneId: sub_zone_id, placement: request_var, source: 'monetag_postback' },
      holdHours: Number(process.env.HOLD_HOURS ?? 24),
    });

    return res.status(200).json({ ok: true, credited: !result.alreadyProcessed, ...result });
  } catch (err) {
    console.error('[monetag webhook] error:', err);
    return res.status(500).json({ error: 'internal_error' });
  }
});
